djangocrud/urls.py
from django.contrib import admin
from django.urls import path
from tasks import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('tasks/', views.tasks, name='tasks'),
    path('tasks_completed/', views.tasks_completed, name='tasks_completed'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    path('create_task/', views.create_task, name='create_task'),
    path('tasks/<int:task_id>', views.task_detail, name='task_detail'),
    path('taks/<int:task_id>/complete', views.complete_task, name='complete_task'),
    path('tasks/<int:task_id>/delete', views.delete_task, name='delete_task'),
    path('about/', views.about, name='about'),
    path('product/', views.product, name='product'),
    path('store/', views.store, name='store'),
    path('blog/', views.blog, name='blog'),
    path('contact/', views.contact, name='contact'),
    path('password_reset/', views.CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('usuarios/', views.user_list, name='user_list'),
    path('editar_usuario/<int:user_id>/', views.editar_usuario, name='editar_usuario'),
    path('activar_usuario/<int:user_id>/', views.activar_usuario, name='activar_usuario'),
    path('desactivar_usuario/<int:user_id>/', views.desactivar_usuario, name='desactivar_usuario'),
    path('ver_perfil/<int:user_id>/', views.ver_perfil, name='ver_perfil'),
    path('servicio1/', views.servicio1, name='servicio1'),
    path('servicio2/', views.servicio2, name='servicio2'),
    path('servicio3/', views.servicio3, name='servicio3'),
    path('manage_user_permissions/<int:user_id>/', views.manage_user_permissions, name='manage_user_permissions'),
    path('cliente-products/', views.cliente_products, name='cliente_products'),
    path('cliente_services/', views.cliente_services, name='cliente_services'),
    path('empleado_home/', views.empleado_home, name='empleado_home'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('shopping-cart/', views.shopping_cart, name='shopping_cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('productos/', views.product_list, name='product_list'),
    path('editar-producto/<int:product_id>/', views.edit_product, name='edit_product'),
    path('eliminar-producto/<int:product_id>/', views.delete_product, name='delete_product'),
    path('add_product/', views.add_product, name='add_product'),
    path('remove-one/<int:product_id>/', views.remove_one, name='remove_one'),
    path('remove-all/<int:product_id>/', views.remove_all, name='remove_all'),
    path('add-one/<int:product_id>/', views.add_one, name='add_one'),
    path('services/', views.service_list, name='service_list'),
    path('add-service-to-cart/<int:service_id>/', views.add_service_to_cart, name='add_service_to_cart'),
    path('employee/add-service/', views.add_service, name='add_service'),
    path('employee/service-list/', views.employee_service_list, name='employee_service_list'),
    path('services/<int:service_id>/', views.service_detail, name='service_detail'),
    path('edit-service/<int:service_id>/', views.edit_service, name='edit_service'),
    path('delete-service/<int:service_id>/', views.delete_service, name='delete_service'),
    path('services/add_to_cart/<int:service_id>/', views.add_service_to_cart, name='add_service_to_cart'),
    path('adquirir-servicio/<int:servicio_id>/', views.adquirir_servicio, name='adquirir_servicio'),
    path('service-request/<int:service_id>/', views.service_request, name='service_request'),
    path('submit-service-request/<int:service_id>/', views.submit_service_request, name='submit_service_request'),
    path('request-service/<int:service_id>/', views.ServiceRequestView.as_view(), name='request_service'),
    path('pedidos/', views.pedido_list, name='pedido_list'),
    path('buy-products/', views.buy_products, name='buy_products'),
    path('eliminar_pedido/<int:pedido_id>/', views.eliminar_pedido, name='eliminar_pedido'),
    path('detalles_pedido/<int:pedido_id>/', views.detalles_pedido, name='detalles_pedido'),
    path('eliminacion_confirmada/', views.eliminacion_confirmada, name='eliminacion_confirmada'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.core.validators import validate_email
from django.contrib.auth import get_user_model
from django.utils import timezone

# Create your models here.

class Task(models.Model):
  title = models.CharField(max_length=200)
  description = models.TextField(max_length=1000)
  created = models.DateTimeField(auto_now_add=True)
  datecompleted = models.DateTimeField(null=True, blank=True)
  important = models.BooleanField(default=False)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

  def __str__(self):
    return self.title + ' - ' + self.user.username

    
class CustomUser(AbstractUser):
    ROLES = (
        ('admin', 'Administrador'),
        ('empleado', 'Empleado'),
        ('cliente', 'Cliente'),
    )
    role = models.CharField(max_length=20, choices=ROLES, default='cliente')
    email = models.EmailField(unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'role']

class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name
    
    
class ShoppingCart(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE, unique=True)
    products = models.ManyToManyField('Product', through='CartItem')
    direccion_envio = models.CharField(max_length=255, default='')

    def __str__(self):
        return f"Carrito de {self.user.username}"


class Service(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    created_by = models.ForeignKey(get_user_model(), on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

class CartItem(models.Model):
    cart = models.ForeignKey('ShoppingCart', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, null=True, blank=True, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, null=True, blank=True, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.quantity} x {self.product.name if self.product else self.service.name}"

    @property
    def total(self):
        # Lógica para calcular el total
        return self.quantity * self.product.price if self.product else self.quantity * self.service.price

    @total.setter
    def total(self, value):
        # No hacemos nada aquí, ya que el total se calcula automáticamente
        pass

# models.py

class Pedido(models.Model):
    servicios = models.ManyToManyField(Service, blank=True)
    nombre_completo = models.CharField(max_length=255)
    tipo_documento = models.CharField(max_length=50)
    numero_documento = models.CharField(max_length=50)
    correo_electronico = models.EmailField()
    numero_celular = models.CharField(max_length=20)
    direccion = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Pedido para {self.nombre_completo}"




class ServiceRequest(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='service_requests', default=1)  # Ajusta el valor predeterminado según tus necesidades
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255)
    document_type = models.CharField(max_length=50)
    document_number = models.CharField(max_length=20)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20)
    address = models.TextField()

    def __str__(self):
        return f"Solicitud de servicio para {self.full_name}"
    
class PedidoProducto(models.Model):
    productos = models.ManyToManyField(Product, blank=True)
    nombre_completo = models.CharField(max_length=255)
    tipo_documento = models.CharField(max_length=50)
    numero_documento = models.CharField(max_length=50)
    correo_electronico = models.EmailField()
    numero_celular = models.CharField(max_length=20)
    direccion = models.TextField()
    fecha_creacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Pedido de productos para {self.nombre_completo}"

tasks/forms.py
# forms.py

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import *

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'important']
      
        
class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'password1', 'password2', ]

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = CustomUser

class CustomUserForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['username', 'email', 'role']

class UserPermissionForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['is_superuser', 'is_staff']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ['name', 'description', 'price']  # Ajusta los campos según tu modelo

    # Puedes agregar más personalización del formulario aquí si es necesario
    
class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        fields = ['nombre_completo', 'tipo_documento', 'numero_documento', 'correo_electronico', 'numero_celular', 'direccion']

class ServiceRequestForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ['full_name', 'document_type', 'document_number', 'email', 'phone_number', 'address',]
        
class ShoppingCartForm(forms.Form):
    # Puedes agregar más campos según tus necesidades
    direccion_envio = forms.CharField(label='Dirección de Envío', max_length=255)
    comentario = forms.CharField(label='Comentario', widget=forms.Textarea, required=False)

tasks/templates/contact.html
{% extends 'base.html' %} {% block content %} {% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/main.js' %}"></script>
</head>
<body>
       <!-- Page Header Start -->
       <div class="container-fluid page-header py-5 mb-5 wow fadeIn" data-wow-delay="0.1s" style="background-color: #F1FFF2;">
        <div class="container text-center py-5">
            <h1 class="display-2 text-dark mb-4 animated slideInDown" style="background-color: #DEFFDD; padding: 10px; border-radius: 8px; color: white;">Contactos</h1>
            <nav aria-label="breadcrumb animated slideInDown">
                <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item"><a href="/">Inicio</a></li>
                    <li class="breadcrumb-item"><a href="/about">Acerca de nosotros</a></li>
                    <li class="breadcrumb-item"><a href="/product">Productos</a></li>
                    <li class="breadcrumb-item"><a href="/store">Servicios</a></li>
                    <li class="breadcrumb-item text-dark" aria-current="page">Contacto</li>
                </ol>
            </nav>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Contact Start -->
    <div class="container-xxl contact py-5">
        <div class="container">
            <div class="section-title text-center mx-auto wow fadeInUp" data-wow-delay="0.1s" style="max-width: 500px;">
                <p class="fs-5 fw-medium fst-italic text-primary">Contactenos</p>
                <h1 class="display-6">Ponte en contacto con nosotros</h1>
            </div>
            <div class="row g-5 mb-5">
                <div class="col-md-4 text-center wow fadeInUp" data-wow-delay="0.3s">
                    <div class="btn-square mx-auto mb-3">
                        <i class="fa fa-envelope fa-2x text-white"></i>
                    </div>
                    <p class="mb-2">serprefundecolombia@gmail.com</p>
                    <p class="mb-0">serprefundecolombia@outclock.com</p>
                </div>
                <div class="col-md-4 text-center wow fadeInUp" data-wow-delay="0.4s">
                    <div class="btn-square mx-auto mb-3">
                        <i class="fa fa-phone fa-2x text-white"></i>
                    </div>
                    <p class="mb-2">+57 311 242 8075</p>
                    <p class="mb-0">+57 311 504 6747</p>
                </div>
                <div class="col-md-4 text-center wow fadeInUp" data-wow-delay="0.5s">
                    <div class="btn-square mx-auto mb-3">
                        <i class="fa fa-map-marker-alt fa-2x text-white"></i>
                    </div>
                    <p class="mb-2">##</p>
                    <p class="mb-0">Tolima, Ortega</p>
                </div>
            </div>
            <div class="row g-5">
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.1s">
                    <h3 class="mb-4">¿Necesitas mas informacion o que nos pongamos en contacto contigo?</h3>
                    <p class="mb-4">Diligencia el siguiente Formulario correctamente con tus datos y dejanos tu mensaje</a>.</p>
                    <form>
                        <div class="row g-3">
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="name" placeholder="Your Name">
                                    <label for="name">Nombre completo</label>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-floating">
                                    <input type="email" class="form-control" id="email" placeholder="Your Email">
                                    <label for="email">Email</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <input type="text" class="form-control" id="subject" placeholder="Subject">
                                    <label for="subject">Solicitud</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-floating">
                                    <textarea class="form-control" placeholder="Leave a message here" id="message" style="height: 120px"></textarea>
                                    <label for="message">Mensaje</label>
                                </div>
                            </div>
                            <div class="col-12">
                                <button class="btn btn-primary rounded-pill py-3 px-5" type="submit">Enviar Mensaje</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 wow fadeInUp" data-wow-delay="0.5s">
                    <div class="h-100">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7960.816431039348!2d-75.22570540579319!3d3.935896737713298!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8e39389e47bc7a05%3A0xb39b153d4d70910!2sOrtega%2C%20Tolima!5e0!3m2!1ses!2sco!4v1694062058518!5m2!1ses!2sco" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->
</body>
</html>

{% endblock %}

tasks/templates/delete_service.html
{% extends 'base.html' %}

{% block content %}
  <h1>Confirmar Eliminación</h1>
  <p>¿Estás seguro de que deseas eliminar el servicio "{{ service.name }}"?</p>
  
  <form method="post" style="display: inline;">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
  </form>
  
  <a href="{% url 'employee_service_list' %}">Cancelar</a>
{% endblock %}

tasks/templates/detalles_pedido.html
<!-- detalles_pedido.html -->
<h2>Detalles del Pedido</h2>
<p>Cliente: {{ pedido.user.username }}</p>
<p>Servicio: {{ pedido.service.name }}</p>

<!-- Mostrar todos los campos del formulario -->
<p>Nombre Completo: {{ pedido.nombre_completo }}</p>
<p>Tipo de Documento: {{ pedido.tipo_documento }}</p>
<p>Número de Documento: {{ pedido.numero_documento }}</p>
<p>Correo Electrónico: {{ pedido.correo_electronico }}</p>
<p>Número de Celular: {{ pedido.numero_celular }}</p>
<p>Dirección: {{ pedido.direccion }}</p>
<!-- Agrega más campos según sea necesario -->

tasks/templates/edit_product.html
<!-- edit_product.html -->
{% extends 'base.html' %}

{% block content %}
  <h1>Editar Producto</h1>
</style>
<div class="service-request-form-container">
 
  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f5f5f5; /* Color de fondo */
      color: #333; /* Color de texto principal */
      margin: 0;
      padding: 0;
    }
  
    .service-request-form-container {
      max-width: 400px;
      margin: 50px auto;
      background-color: #fff; /* Color de fondo del contenedor del formulario */
      padding: 20px;
      border-radius: 8px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); /* Sombra suave alrededor del contenedor */
    }
  
    h1 {
      color: black; /* Color del título principal */
      text-align: center; /* Centra el texto horizontalmente */
    }
  
    .service-request-form {
      display: flex;
      flex-direction: column;
    }
  
    label {
      margin-bottom: 8px;
    }
  
    input,
    textarea {
      padding: 10px;
      margin-bottom: 15px;
      border: 1px solid #ddd; /* Borde del campo de entrada */
      border-radius: 4px;
      box-sizing: border-box;
      width: 100%;
    }
  
    .submit-btn {
      background-color: #3498db; /* Color de fondo del botón de envío */
      color: #fff; /* Color del texto del botón de envío */
      padding: 12px;
      border: none;
      border-radius: 4px;
      cursor: pointer;
      transition: background-color 0.3s ease-in-out;
    }
  
    button[type="submit"] {
      background-color: #3498db; /* Color de fondo del botón */
      color: #fff; /* Color del texto del botón */
      padding: 12px;
      border: none;
      border-radius: 6px; /* Bordes redondeados */
      cursor: pointer;
      width: 100%;
      transition: background-color 0.3s ease-in-out;
    }
  
    button[type="submit"]:hover {
      background-color: #2980b9; /* Cambia el color al pasar el mouse sobre el botón */
    }s
  </style>
  <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar cambios</button>
  </form>
{% endblock %}

tasks/templates/editar_usuario.html
<!DOCTYPE html>
<html>
    
<head>
    <title>Editar Usuario</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #F0F8FF;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            height: 100vh;
        }

        h1 {
            color: #5e5e5e;
            margin-bottom: 20px;
        }

        form {
            background-color: #ffffff;
            border: 1px solid #dcdcdc;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            width: 300px;
            margin: 20px;
            box-sizing: border-box;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #495057;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            box-sizing: border-box;
            border: 1px solid #ced4da;
            border-radius: 4px;
        }

        button {
            background-color: #66c0f4;
            color: #ffffff;
            padding: 12px 20px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
            display: block;
            font-size: 16px;
        }

        button:hover {
            background-color: #4fa6e5;
        }
    </style>
</head>
<body>
    <h1></h1>
    <form method="post">
     {% csrf_token %}
     {{ form.as_p }}
     <button type="submit">Guardar cambios</button>
 </form>
</body>
</html>

tasks/templates/eliminacion_confirmada.html
<!-- eliminacion_confirmada.html -->
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Eliminación Confirmada</title>
</head>
<body>
    <h1>Pedido Eliminado Exitosamente</h1>
    <p>El pedido ha sido eliminado correctamente.</p>
</body>
</html>
{% endblock %}

tasks/templates/password_reset.html
{% extends "base.html" %}

{% block content %}
  <h1>Cambiar Contraseña</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.email.label_tag }} {{ form.email }}
    <button type="submit">Cambiar Contraseña</button>
  </form>
{% endblock %}

tasks/templates/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
  <h1>Restablecimiento de contraseña completo</h1>
  <p>Su contraseña se ha restablecido correctamente. Pudes ahora <a href="{% url 'signin' %}">sign in</a> con tu nueva contraseña.</p>
{% endblock %}

tasks/templates/service_detail.html
{% extends 'base.html' %}

{% block content %}
  <!-- Tabla para mostrar detalles -->
  <table class="service-details">
    <thead>
      <tr>
        <th>Campo</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Nombre</td>
        <td>{{ service.name }}</td>
      </tr>
      <tr>
        <td>Descripción</td>
        <td>{{ service.description }}</td>
      </tr>
      <tr>
        <td>Precio</td>
        <td>${{ service.price }}</td>
      </tr>
      <!-- Agrega más filas según sea necesario -->
    </tbody>
  </table>
  <!-- Fin de la tabla -->

  <!-- Otros detalles que desees mostrar -->
{% endblock %}

<style>
  /* Estilos para la tabla */
  .service-details {
    width: 100%;
    border-collapse: collapse;
    margin-top: 20px;
  }

  .service-details th, .service-details td {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: left;
  }

  .service-details th {
    background-color: #f2f2f2;
  }
</style>

tasks/templates/task_detail.html
{% extends 'base.html' %}

{% block content %}

{{task.title}}

{{error}}

<form method="POST">
  {% csrf_token %}
  {{form.as_p}}

  <button>
    Update
  </button>
</form>

<form action="{% url 'complete_task' task.id %}" method="POST">
  {% csrf_token %}
  <button>
    complete
  </button>
</form>

<form action="{% url 'delete_task' task.id %}" method="POST">
  {% csrf_token %}
  <button>
    delete
  </button>
</form>

{% endblock %}

tasks/templates/user_list.html
{% extends 'base.html' %}

{% block content %}
<!DOCTYPE html>
<html>
<head>
    <title>Lista de Usuarios</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h1 {
            color: #5e5e5e;
            margin-bottom: 20px;
        }

        table {
            width: 70%;
            margin: 0 auto;
            border-collapse: collapse;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
        }

        th, td {
            border: 1px solid #dcdcdc;
            padding: 15px;
            text-align: left;
            border-radius: 8px;
        }

        th {
            background-color: #ffffff;
        }

        a {
            color: #007bff;
            text-decoration: none;
            margin-right: 10px;
        }

        a:hover {
            color: #0056b3;
            text-decoration: underline;
        }

        form {
            margin-top: 10px;
        }

        button {
            background-color: #5cb85c;
            color: #ffffff;
            padding: 8px 15px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-right: 10px;
        }

        button:hover {
            background-color: #4cae4c;
        }

        a.button {
            display: inline-block;
            background-color: #007bff;
            color: #ffffff;
            padding: 8px 15px;
            text-decoration: none;
            border-radius: 4px;
            margin-top: 20px;
        }

        a.button:hover {
            background-color: #0056b3;
        }
    </style>
</head> 
<body>
    <h1>Lista de Usuarios</h1>
    <table>
        <tr>
            <th>Usuario</th>
            <th>Rol</th>
            <th>Acciones</th>
        </tr>
        {% for user_with_permissions in users_with_permissions %}
            <tr>
                <td>{{ user_with_permissions.user.username }}</td>
                <td>{{ user_with_permissions.user.get_role_display }}</td>
                <td>
                    <a href="{% url 'editar_usuario' user_with_permissions.user.id %}">Editar</a>

                    {% if user_with_permissions.user.role == 'admin' or user_with_permissions.user.role == 'empleado' %}
                        <form action="{% url 'manage_user_permissions' user_with_permissions.user.id %}" method="post">
                            {% csrf_token %}
                            {{ user_with_permissions.form.as_p }}
                            <button type="submit">Guardar Permisos</button>
                        </form>
                    {% endif %}

                    {% if user_with_permissions.user.is_active %}
                        <form action="{% url 'desactivar_usuario' user_with_permissions.user.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Desactivar</button>
                        </form>
                    {% else %}
                        <form action="{% url 'activar_usuario' user_with_permissions.user.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Activar</button>
                        </form>
                    {% endif %}

                    <a href="{% url 'ver_perfil' user_with_permissions.user.id %}">Ver perfil</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</body>
</html>
{% endblock %}